version: '3.4'
services:
  mysql:
    hostname: mysql
    image: 'mysql:latest'
    ports:
      - "5040:5040"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: ndjchrfK.1
      MYSQL_DATABASE: school